<?php

namespace Database\Seeders;

use DB;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class NotariaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('notarias')->delete();

        \DB::table('notarias')->insert(array (
            0 =>
            array (
                'id' => 397,
                'numero' => 1,
                'notario' => 'JOSE SOLORZANO HERREJON',
                'email' => 'not1solorzano@hotmail.com',
                'rfc' => 'SOHJ640917IKA',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            1 =>
            array (
                'id' => 398,
                'numero' => 2,
                'notario' => 'LUIS FERNANDO ALCOCER MEDINA',
                'email' => 'gestorias@notaria2.mx',
                'rfc' => 'AOML7804226W9',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            2 =>
            array (
                'id' => 399,
                'numero' => 3,
                'notario' => 'EDGAR FERNANDO RUÍZ BASTIEN',
                'email' => 'edgar_frb2006@yahoo.com.mx',
                'rfc' => 'RUBE560520JB1',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            3 =>
            array (
                'id' => 400,
                'numero' => 4,
                'notario' => 'XAVIER E. PATIÑO OSEGUERA',
                'email' => 'np04.mich@outlook.com',
                'rfc' => 'PAOX810529AL8',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            4 =>
            array (
                'id' => 401,
                'numero' => 5,
                'notario' => 'HILDA NAVARRO SKINFIELD',
                'email' => 'notaria.5.mich@hotmail.com',
                'rfc' => 'NASH420704PC2',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            5 =>
            array (
                'id' => 402,
                'numero' => 6,
                'notario' => 'DAVID GÁLVEZ HERNÁNDEZ',
                'email' => 'kaligaab@hotmail.com',
                'rfc' => 'GAHD470628Q14',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            6 =>
            array (
                'id' => 403,
                'numero' => 7,
                'notario' => 'JUAN ADOLFO CANO ACEVES',
                'email' => 'isr@notariasiete.mx',
                'rfc' => 'CAAJ870620KH3',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            7 =>
            array (
                'id' => 404,
                'numero' => 8,
                'notario' => 'JOSÉ JAÍME MARES CAMARENA',
                'email' => 'notariaocholapiedad@hotmail.com',
                'rfc' => 'MACJ541223125',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            8 =>
            array (
                'id' => 405,
                'numero' => 9,
                'notario' => 'ENRIQUE GUDIÑO MAGAÑA',
                'email' => 'notarionueve@hotmail.com',
                'rfc' => 'GUME5412228RA',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            9 =>
            array (
                'id' => 406,
                'numero' => 10,
                'notario' => 'Luis Christian Ríos Vargas',
                'email' => 'notariadiez@outlook.es',
                'rfc' => 'RIVL800208NTA',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            10 =>
            array (
                'id' => 407,
                'numero' => 11,
                'notario' => 'LUIS LOYA ALCALÁ',
                'email' => 'luisloya@notariaoncemich.com',
                'rfc' => 'LOAL5604243RA',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            11 =>
            array (
                'id' => 408,
                'numero' => 12,
                'notario' => 'ARMANDO ARRIAGA DIAZ',
                'email' => 'aina_not12@yahoo.com.mx',
                'rfc' => 'AIDA680415712',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            12 =>
            array (
                'id' => 409,
                'numero' => 13,
                'notario' => 'PAVEL AURELIO OCEGUEDA ROBLEDO',
                'email' => 'notariaocegueda13@gmail.com',
                'rfc' => 'OERP770714JC7',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            13 =>
            array (
                'id' => 410,
                'numero' => 14,
                'notario' => 'PATRICIA S. SERVÍN MALDONADO',
                'email' => 'servinmaldonadopatricia@gmail.com',
                'rfc' => 'SEMP620821TPA',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            14 =>
            array (
                'id' => 411,
                'numero' => 15,
                'notario' => 'JORGE MENDOZA ALVAREZ',
                'email' => 'notariapub.15@gmail.com',
                'rfc' => 'MEAJ380605P19',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            15 =>
            array (
                'id' => 412,
                'numero' => 16,
                'notario' => 'LIC J. JESUS MAGAÑA TORRES',
                'email' => 'notario16mich@hotmail.com',
                'rfc' => 'MATJ630202MN8',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            16 =>
            array (
                'id' => 413,
                'numero' => 17,
                'notario' => 'FAUSTO RICARDO GONZÁLEZ RODRÍGUEZ',
                'email' => 'notaria_17@hotmail.com',
                'rfc' => 'GORF680401PQA',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            17 =>
            array (
                'id' => 414,
                'numero' => 18,
            'notario' => 'CARLOS MARTINEZ GARCIA DE LEON (SUST.)',
                'email' => 'jluisrizol@hotmail.com',
                'rfc' => 'MAAF361010LN7',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            18 =>
            array (
                'id' => 415,
                'numero' => 19,
                'notario' => 'EDUARDO CHAVEZ  CARREÓN',
                'email' => 'eduardochcarreon@gmail.com',
                'rfc' => 'CACE590209Q17',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            19 =>
            array (
                'id' => 416,
                'numero' => 20,
                'notario' => 'ELISEO GILDARDO SÁNCHEZ VALERIO',
                'email' => 'notaria20zinapecuaro@gmail.com',
                'rfc' => 'SAVE620915642',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            20 =>
            array (
                'id' => 417,
                'numero' => 21,
                'notario' => 'JOSÉ PEÑA LOPEZ',
                'email' => 'trasladosnotaria21@hotmail.com',
                'rfc' => 'PELJ570709CA4',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            21 =>
            array (
                'id' => 418,
                'numero' => 22,
                'notario' => 'ISMAEL SIGALA PÁEZ',
                'email' => 'notaria22uruapan@gmail.com',
                'rfc' => 'SIPI751127GK8',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            22 =>
            array (
                'id' => 419,
                'numero' => 23,
                'notario' => 'JUAN CUTBERTO TENORIO GONZÁLEZ',
                'email' => 'notario23jm@prodigy.net.mx',
                'rfc' => 'TEGJ640624LJ4',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            23 =>
            array (
                'id' => 420,
                'numero' => 24,
                'notario' => 'DANIEL ALEJANDRO HERNANDEZ CHAVEZ',
                'email' => 'Yolandaea.notaria24@gmail.com',
                'rfc' => 'HECD8502016Q7',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            24 =>
            array (
                'id' => 421,
                'numero' => 25,
            'notario' => 'MARÍA DE LOS ANGELES GUZMÁN MURILLO (ADS)',
                'email' => 'notaria25.michoacan@gmail.com',
                'rfc' => 'GUMA511130GG6',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            25 =>
            array (
                'id' => 422,
                'numero' => 26,
                'notario' => 'OSCAR VIDAL ALCÁNTAR RAMÍREZ',
                'email' => 'notaria_26@hotmail.com',
                'rfc' => 'AARO6707068X2',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            26 =>
            array (
                'id' => 423,
                'numero' => 27,
                'notario' => 'GENARO CAMPOS GARCIA',
                'email' => 'notariap27@outlook.com',
                'rfc' => 'GAGG7810264V2',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            27 =>
            array (
                'id' => 424,
                'numero' => 28,
                'notario' => 'LILIANA PINEDA RUIZ',
                'email' => 'vicentepineda28@hotmail.com',
                'rfc' => 'PIRL720314IH9',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            28 =>
            array (
                'id' => 425,
                'numero' => 29,
                'notario' => 'BONIFACIO FUENTES HERRERA',
                'email' => 'not29_uruapan@hotmail.com',
                'rfc' => 'FUHB721001JZ6',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            29 =>
            array (
                'id' => 426,
                'numero' => 30,
                'notario' => 'JUAN CARLOS BOLAÑOS ABRAHAM',
                'email' => 'traslados@notaria30mlm.mx',
                'rfc' => 'BOAJ730113870',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            30 =>
            array (
                'id' => 427,
                'numero' => 31,
                'notario' => 'JOSE ANTONIO RAMÍREZ CHAVARRIA',
                'email' => 'notaria31michoacan@outlook.com',
                'rfc' => 'RACA700330FR0',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            31 =>
            array (
                'id' => 428,
                'numero' => 32,
                'notario' => 'JUÁN CARLOS SANDOVAL RUIZ',
                'email' => 'notaria32@hotmail.com',
                'rfc' => 'SARJ72061651A',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            32 =>
            array (
                'id' => 429,
                'numero' => 33,
                'notario' => 'LUIS FERNANDO TREVIÑO JACOBO',
                'email' => 'gestionnot33@hotmail.com',
                'rfc' => 'TEJL811122JA1',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            33 =>
            array (
                'id' => 430,
                'numero' => 34,
            'notario' => 'M. EN D. FRANCISCO ESTEBAN PÉREZ MEDINA (SUST.)',
                'email' => 'notaria34morelia@gmail.com',
                'rfc' => 'PEMF721220NG4',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            34 =>
            array (
                'id' => 431,
                'numero' => 35,
                'notario' => 'GUILLERMO LOAIZA GOMEZ',
                'email' => 'bjpgama@gmail.com',
                'rfc' => 'LOGG900311IX5',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            35 =>
            array (
                'id' => 432,
                'numero' => 36,
                'notario' => 'CARMEN REYES REYNOSO',
                'email' => 'notaria_36_michoacan@hotmail.com',
                'rfc' => 'RERC6509035R8',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            36 =>
            array (
                'id' => 433,
                'numero' => 37,
                'notario' => 'GERARDO ALCARAZ MONTES',
                'email' => 'not37zacapu@hotmail.com',
                'rfc' => 'AAMG580426HX8',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            37 =>
            array (
                'id' => 434,
                'numero' => 38,
                'notario' => 'JOSÉ MAURICIO MORALES SÁNCHEZ',
                'email' => 'notario38@hotmail.com',
                'rfc' => 'MOSM851216IH2',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            38 =>
            array (
                'id' => 435,
                'numero' => 39,
                'notario' => 'CARLOS ALBERTO GALLEGOS PEÑA',
                'email' => 'magabar39@hotmail.com',
                'rfc' => 'GAPC660701513',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            39 =>
            array (
                'id' => 436,
                'numero' => 40,
                'notario' => 'CARLOS TENA MORA',
                'email' => 'not.40.ario@gmail.com',
                'rfc' => 'TEMC460723DI1',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            40 =>
            array (
                'id' => 437,
                'numero' => 41,
                'notario' => 'LUIS PEDRAZA RODRIGUEZ',
                'email' => 'lanotaria_41@hotmail.com',
                'rfc' => 'PERL441117NL5',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            41 =>
            array (
                'id' => 438,
                'numero' => 42,
                'notario' => 'EDUARDO ESTRADA GARCÍA',
                'email' => 'estradecus@hotmail.com',
                'rfc' => 'EAGE610301452',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            42 =>
            array (
                'id' => 439,
                'numero' => 43,
                'notario' => 'MANUEL MORENO BARRAGÁN',
                'email' => 'licmoreno43@hotmail.com',
                'rfc' => 'MOBM660505G65',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            43 =>
            array (
                'id' => 440,
                'numero' => 44,
                'notario' => 'ALEJANDRO TINOCO ALVAREZ',
                'email' => 'notario.publico@yahoo.com.mx',
                'rfc' => 'TIAA750529SH6',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            44 =>
            array (
                'id' => 441,
                'numero' => 45,
                'notario' => 'ERIK LÓPEZ LÓPEZ',
                'email' => 'notaria45catastro@gmail.com',
                'rfc' => 'LOLE670403EE6',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            45 =>
            array (
                'id' => 442,
                'numero' => 46,
                'notario' => 'MANUEL NAVARRO MENDOZA',
                'email' => 'navarro46notaria@hotmail.com',
                'rfc' => 'NAMM710303R79',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            46 =>
            array (
                'id' => 444,
                'numero' => 48,
                'notario' => 'EDUARDO CHÁVEZ Y LÓPEZ',
                'email' => 'notaria48eduardo@gmail.com',
                'rfc' => 'CALE460719SL3',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            47 =>
            array (
                'id' => 445,
                'numero' => 49,
                'notario' => 'JORGE OCTAVIO OROPEZA SOTO',
                'email' => 'notaria_49@live.com',
                'rfc' => 'OOSJ420922U88',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            48 =>
            array (
                'id' => 446,
                'numero' => 50,
                'notario' => 'MOISES ESPINOSA RUÍZ',
                'email' => 'notaria50mich@gmail.com',
                'rfc' => 'EIRM630630CB9',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            49 =>
            array (
                'id' => 447,
                'numero' => 51,
                'notario' => 'LAURA GONZÁLEZ MARTINEZ',
                'email' => 'notaria51_1@hotmail.com',
                'rfc' => 'GOML710423LA6',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            50 =>
            array (
                'id' => 448,
                'numero' => 52,
                'notario' => 'OCTAVIO PEÑA MIGUEL',
                'email' => 'tramitesenlinea@notaria52morelia.com',
                'rfc' => 'PEMO680801QU9',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            51 =>
            array (
                'id' => 449,
                'numero' => 53,
                'notario' => 'EFRÉN CONTRERAS GAITÁN',
                'email' => 'gestoria@notaria53michoacan.mx',
                'rfc' => 'COGX710830P39',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            52 =>
            array (
                'id' => 450,
                'numero' => 54,
                'notario' => 'EDUARDO ARTURO ESTRADA CARRILLO',
                'email' => 'notariapublica54moreliamich@hotmail.com',
                'rfc' => 'EACE670616EJ7',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            53 =>
            array (
                'id' => 451,
                'numero' => 55,
                'notario' => 'JORGE ARTURO BOLAÑOS ABRAHAM',
                'email' => 'notaria55michoacan@hotmail.com',
                'rfc' => 'BOAJ7312269K7',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            54 =>
            array (
                'id' => 452,
                'numero' => 56,
                'notario' => 'FERNANDO PULIDO MACIEL',
                'email' => 'notarianumero56@gmail.com',
                'rfc' => 'PUMF831026FN1',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            55 =>
            array (
                'id' => 453,
                'numero' => 57,
                'notario' => 'FRANCISCO IVAN TENORIO ROJAS',
                'email' => 'notario57zit@gmail.com',
                'rfc' => 'TERF9201112H9',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            56 =>
            array (
                'id' => 454,
                'numero' => 58,
                'notario' => 'ANA MARIELA SERVÍN PITA',
                'email' => 'notariapublica_58@hotmail.com',
                'rfc' => 'SEPA710406KXA',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            57 =>
            array (
                'id' => 455,
                'numero' => 59,
                'notario' => 'LUIS JAIME LÓPEZ OCHOA',
                'email' => 'notaria59@prodigy.net.mx',
                'rfc' => 'LOOL480804HZ8',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            58 =>
            array (
                'id' => 456,
                'numero' => 60,
                'notario' => 'MARGARITA CANO VILLALÓN',
                'email' => 'notaria60_cano@yahoo.com.mx',
                'rfc' => 'CAVM710513I62',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            59 =>
            array (
                'id' => 457,
                'numero' => 61,
                'notario' => 'ALAN ISRAEL ARAIZA LOPEZ',
                'email' => 'notaria61_araiza@hotmail.com',
                'rfc' => 'AALA8404132J0',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            60 =>
            array (
                'id' => 458,
                'numero' => 62,
                'notario' => 'LOURDES ESPERANZA MARTÍNEZ ARAGÓN',
                'email' => 'notaria62mich@hotmail.com',
                'rfc' => 'MAAL650821CM6',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            61 =>
            array (
                'id' => 459,
                'numero' => 63,
                'notario' => 'LIC. ISMAEL EDUARDO SUAREZ ABREGO',
                'email' => 'notariapublica63lzc@gmail.com',
                'rfc' => 'SUAI4906202N29',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            62 =>
            array (
                'id' => 460,
                'numero' => 64,
                'notario' => 'DAVID FRANCO SANCHEZ',
                'email' => 'notario64morelia@gmail.com',
                'rfc' => 'FASD711117T32',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            63 =>
            array (
                'id' => 461,
                'numero' => 65,
                'notario' => 'LIC. ALEJANDRA GARCIA CUEVAS',
                'email' => 'lic.alecuevas65@gmail.com',
                'rfc' => 'GACA650601RN1',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            64 =>
            array (
                'id' => 462,
                'numero' => 66,
                'notario' => 'LIC. CORNELIO JONATHAN VILLASEÑOR CHAVEZ',
                'email' => 'TRASLADOSNOTARIA66@hotmail.com',
                'rfc' => 'VICC750101Q19',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            65 =>
            array (
                'id' => 463,
                'numero' => 67,
                'notario' => 'IGNACIO BARRERA PAZ',
                'email' => 'ibarrera@hotmail.com',
                'rfc' => 'BAPI721212CH3',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            66 =>
            array (
                'id' => 465,
                'numero' => 69,
                'notario' => 'LEONARDO SERVÍN MALDONADO',
                'email' => 'notaria_69_zinapecuaro@hotmail.com',
                'rfc' => 'SEML7004244V2',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            67 =>
            array (
                'id' => 466,
                'numero' => 70,
                'notario' => 'GUILLERMO E. RUÍZ CONTRERAS',
                'email' => 'notariapub70@msn.com',
                'rfc' => 'RUCG830329KA8',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            68 =>
            array (
                'id' => 467,
                'numero' => 71,
                'notario' => 'GUADALUPE SUÁREZ JUÁREZ',
                'email' => 'notaria71.mich@gmail.com',
                'rfc' => 'SUJG660510SE5',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            69 =>
            array (
                'id' => 468,
                'numero' => 72,
                'notario' => 'YOLANDA FLORES MARCIAL',
                'email' => 'notaria72coalcoman@hotmail.com',
                'rfc' => 'FOMY550805DH7',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            70 =>
            array (
                'id' => 469,
                'numero' => 73,
                'notario' => 'JOSÉ ALFONSO ESPINOSA RUÍZ',
                'email' => 'notaria73mich@yahoo.com.mx',
                'rfc' => 'EIRA660508S50',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            71 =>
            array (
                'id' => 470,
                'numero' => 74,
                'notario' => 'CARLOS FÉLIX LÓPEZ MACIEL',
                'email' => 'notno74@prodigy.net.mx',
                'rfc' => 'LOMC760825874',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            72 =>
            array (
                'id' => 471,
                'numero' => 75,
                'notario' => 'MIGUEL ANGEL VÁZQUEZ HERRERA',
                'email' => 'notaria75@hotmail.com',
                'rfc' => 'VAHM540306J46',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            73 =>
            array (
                'id' => 472,
                'numero' => 76,
                'notario' => 'NOEMY AGUILAR ZANABRIA',
                'email' => 'tdnotaria76@hotmail.com',
                'rfc' => 'AUZN730623Q93',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            74 =>
            array (
                'id' => 473,
                'numero' => 77,
                'notario' => 'MAURICIO PIÑA REYNA',
                'email' => 'notariapublica77quiroga@gmail.com',
                'rfc' => 'PIRM660327CG1',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            75 =>
            array (
                'id' => 474,
                'numero' => 78,
                'notario' => 'JOSE DAVID PEDRO MATEO',
                'email' => 'notariapublica78michoacan@hotmail.com',
                'rfc' => 'PEMD8205061Z5',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            76 =>
            array (
                'id' => 475,
                'numero' => 79,
                'notario' => 'GONZÁLO FERNÁNDEZ MÉNDEZ',
                'email' => 'notariapub79@gmail.com',
                'rfc' => 'FEMG5003051G6',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            77 =>
            array (
                'id' => 476,
                'numero' => 80,
                'notario' => 'JAVIER ANTONIO MORA MARTINEZ',
                'email' => 'notariapublica80sahuayo@gmail.com',
                'rfc' => 'MOMJ8212278G2',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            78 =>
            array (
                'id' => 477,
                'numero' => 81,
                'notario' => 'VICENTE LUIS COCA ALVAREZ',
                'email' => 'notariapublica81@hotmail.com',
                'rfc' => 'COAV480621SJ5',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            79 =>
            array (
                'id' => 478,
                'numero' => 82,
                'notario' => 'PATRICIA HERNÁNDEZ ARTEAGA',
                'email' => 'notariapublica_82@hotmail.com',
                'rfc' => 'HEAP720606D17',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            80 =>
            array (
                'id' => 479,
                'numero' => 83,
                'notario' => 'LIC. ERNESTO CONTRERAS REYES',
                'email' => 'notariap83@gmail.com',
                'rfc' => 'CORE420322IBA',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            81 =>
            array (
                'id' => 480,
                'numero' => 84,
                'notario' => 'HELENA BARRIGA GUTIERREZ',
                'email' => 'notariapublica84@live.com.mx',
                'rfc' => 'BAGH630719NM8',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            82 =>
            array (
                'id' => 481,
                'numero' => 85,
                'notario' => 'ALEJANDRO JAIME MORA LÓPEZ',
                'email' => 'notaria.85@hotmail.com',
                'rfc' => 'MOLA4207101E9',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            83 =>
            array (
                'id' => 482,
                'numero' => 86,
                'notario' => 'LEONARDO PEDRAZA HINOJOSA',
                'email' => 'contabilidadnotaria86@gmail.com',
                'rfc' => 'PEHL680805CAA',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            84 =>
            array (
                'id' => 483,
                'numero' => 87,
                'notario' => 'GABRIELA ARCOS NAVARRO',
                'email' => 'gabarc2030@gmail.com',
                'rfc' => 'AONG800929JB6',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            85 =>
            array (
                'id' => 484,
                'numero' => 88,
            'notario' => 'SELENE SACNICTÉ RUVALCABA LÓPEZ (ADS)',
                'email' => 'notaria_88_michoacan@hotmail.com',
                'rfc' => 'RULS801002CA8',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            86 =>
            array (
                'id' => 485,
                'numero' => 89,
                'notario' => 'MARIA DEL ROCIO GONZÁLEZ VELEZ ALDANA',
                'email' => 'notaria.89@hotmail.com',
                'rfc' => 'GOAR520628TL8',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            87 =>
            array (
                'id' => 486,
                'numero' => 90,
                'notario' => 'LIC. IGNACIO M. SANDOVAL HDZ.',
                'email' => 'notaria90patz@gmail.com',
                'rfc' => 'SAHI6905217R0',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            88 =>
            array (
                'id' => 487,
                'numero' => 91,
                'notario' => 'CLAUDIA ANGÉLICA ZEPEDA AGUILAR',
                'email' => 'claudianotaria91@gmail.com',
                'rfc' => 'ZEAC781218813',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            89 =>
            array (
                'id' => 488,
                'numero' => 92,
                'notario' => 'MARÍA TERESA HERNANDEZ GARCÍA',
                'email' => 'notaria92.traslados@gmail.com',
                'rfc' => 'HEGT780119JV6',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            90 =>
            array (
                'id' => 489,
                'numero' => 93,
                'notario' => 'CARLOS SINHUE VITAL PUNZO',
                'email' => 'revisiontrasladosnot93@gmail.com',
                'rfc' => 'VIPC750809S67',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            91 =>
            array (
                'id' => 490,
                'numero' => 94,
                'notario' => 'YADIRA ESTELA NÚÑEZ AGUILAR',
                'email' => 'notaria94traslados@gmail.com',
                'rfc' => 'NUAY711021FJ3',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            92 =>
            array (
                'id' => 491,
                'numero' => 95,
                'notario' => 'M. EN D. MARCO VINICIO AGUILERA GARIBAY',
                'email' => 'catastro@notaria95mich.com',
                'rfc' => 'AUGM680318619',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            93 =>
            array (
                'id' => 492,
                'numero' => 96,
                'notario' => 'LIC. EDUARDO ROSAS LARIOS',
                'email' => 'erlnotario96zamoramich@outlook.com',
                'rfc' => 'ROLE690108DD1',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            94 =>
            array (
                'id' => 493,
                'numero' => 97,
                'notario' => 'ISANIA LISBETH SOLORZANO SUAREZ',
                'email' => 'notaria97@hotmail.com',
                'rfc' => 'SOSI850314M20',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            95 =>
            array (
                'id' => 494,
                'numero' => 98,
                'notario' => 'JUAN M. MALDONADO VALENCIA',
                'email' => 'micklys@hotmail.com',
                'rfc' => 'MAVJ490326H15',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            96 =>
            array (
                'id' => 495,
                'numero' => 99,
                'notario' => 'RUBÉN ALEJANDRO MORELOS PRADO',
                'email' => 'trasladosnot99mich@hotmail.com',
                'rfc' => 'MOPR580516SV3',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            97 =>
            array (
                'id' => 496,
                'numero' => 100,
                'notario' => 'SALVADOR ZÚÑIGA ANDRADE',
                'email' => 'sazuan@yahoo.com',
                'rfc' => 'ZUAS480530GVA',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            98 =>
            array (
                'id' => 497,
                'numero' => 101,
                'notario' => 'ALFREDO ONTIVEROS CASTILLO',
                'email' => 'not101@prodigy.net.mx',
                'rfc' => 'OICA600810LJ9',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            99 =>
            array (
                'id' => 498,
                'numero' => 102,
                'notario' => 'CARLOS ARMANDO MAGAÑA MARTÍNEZ',
                'email' => 'lic.carlos.magana@notariapublica102.com',
                'rfc' => 'MAMC440312HP9',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            100 =>
            array (
                'id' => 499,
                'numero' => 103,
                'notario' => 'JESUS SOLORZANO OCHOA',
                'email' => 'solo8a@gmail.com',
                'rfc' => 'SOOJ681218NP4',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            101 =>
            array (
                'id' => 501,
                'numero' => 105,
                'notario' => 'M. ALFREDO PALOMARES ESTRADA',
                'email' => 'notaria105@yahoo.com.mx',
                'rfc' => 'PAEM620716146',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            102 =>
            array (
                'id' => 502,
                'numero' => 106,
                'notario' => 'RUBEN PEREZ GALLARDO OJEDA',
                'email' => 'traslados-not106@hotmail.com',
                'rfc' => 'PEOR580808578',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            103 =>
            array (
                'id' => 503,
                'numero' => 107,
                'notario' => 'GILBERTO RIVERA ORTIZ',
                'email' => 'not.grim@hotmail.com',
                'rfc' => 'RIOG8001302Q9',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            104 =>
            array (
                'id' => 504,
                'numero' => 108,
                'notario' => 'SERGIO ARTURO PARRA CARRANZA',
                'email' => 'notariapublica_108@hotmail.com',
                'rfc' => 'PACS581210LP5',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            105 =>
            array (
                'id' => 505,
                'numero' => 109,
                'notario' => 'ADOLFO TRUJILLO MARTÍNEZ',
                'email' => 'notaria_109@hotmail.com',
                'rfc' => 'TUMA740510JB7',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            106 =>
            array (
                'id' => 506,
                'numero' => 110,
                'notario' => 'LIC. MARISOL GARCÍA MARTÍNEZ',
                'email' => 'notaria110_2@hotmail.com',
                'rfc' => 'GAMM780806AD0',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            107 =>
            array (
                'id' => 507,
                'numero' => 111,
                'notario' => 'KARLA DEL RÍO VILLASEÑOR',
                'email' => 'kdrv241@hotmail.com',
                'rfc' => 'RIVK770514KM2',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            108 =>
            array (
                'id' => 508,
                'numero' => 112,
                'notario' => 'ROBERTO CERDA ACOSTA',
                'email' => 'rca@notaria112mich.mx',
                'rfc' => 'CEAR661118712',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            109 =>
            array (
                'id' => 509,
                'numero' => 113,
                'notario' => 'JOSÉ MAURO CISNEROS FONSECA',
                'email' => 'notaria113@hotmail.com',
                'rfc' => 'CIFM500719F64',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            110 =>
            array (
                'id' => 510,
                'numero' => 114,
                'notario' => 'LIC. WENDY REYES VARGAS',
                'email' => 'notaria_114@hotmail.com',
                'rfc' => 'REVW710802AP7',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            111 =>
            array (
                'id' => 511,
                'numero' => 115,
                'notario' => 'JAIME MORALES MORFÍN',
                'email' => 'jmmnot-115@outlook.com',
                'rfc' => 'MOMJ500518AM6',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            112 =>
            array (
                'id' => 512,
                'numero' => 116,
                'notario' => 'EDGAR HIRAM DAMÍAN BRAVO',
                'email' => 'notpub116@hotmail.com',
                'rfc' => 'DABL520510MA1',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            113 =>
            array (
                'id' => 513,
                'numero' => 117,
                'notario' => 'JAVIER FLORES DE JESÚS',
                'email' => 'javiernotario117@hotmail.com',
                'rfc' => 'FOJJ6709256ZA',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            114 =>
            array (
                'id' => 514,
                'numero' => 118,
                'notario' => 'DANIEL TRUJILLO MARTÍNEZ',
                'email' => 'notaria.118.mich@hotmail.com',
                'rfc' => 'TUMD790607GD1',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            115 =>
            array (
                'id' => 515,
                'numero' => 119,
                'notario' => 'ERNESTINA AVILA PEDRAZA',
                'email' => 'notaria-119@hotmail.com',
                'rfc' => 'AIPE701022UH3',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            116 =>
            array (
                'id' => 516,
                'numero' => 120,
                'notario' => 'CYNTHIA GABRIELA BALLINAS OCHARÁN',
                'email' => 'tramitesnotaria120@yahoo.com',
                'rfc' => 'BAOC690916MQ3',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            117 =>
            array (
                'id' => 518,
                'numero' => 122,
                'notario' => 'MA. AZUCENA CHÁVEZ GUIZAR',
                'email' => 'notaria_122@hotmail.com',
                'rfc' => 'CAGX670821A23',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            118 =>
            array (
                'id' => 519,
                'numero' => 123,
                'notario' => 'LUIS CARLOS GARCÍA ESTEFAN',
                'email' => 'lcge@prodigy.net.mx',
                'rfc' => 'GAEL711117Q36',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            119 =>
            array (
                'id' => 520,
                'numero' => 124,
                'notario' => 'SERGIO RUIZ VALENCIA',
                'email' => 'notaria124mich@prodigy.net.mx',
                'rfc' => 'RUVS460905SY1',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            120 =>
            array (
                'id' => 521,
                'numero' => 125,
                'notario' => 'JAVIER TAPIA PAZ',
                'email' => 'notaria125jtp@prodigy.net.mx',
                'rfc' => 'TAPJ691021CD4',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            121 =>
            array (
                'id' => 522,
                'numero' => 126,
                'notario' => 'SERAFÍN TORRES CACHO',
                'email' => 'notariapublica126@yahoo.com.mx',
                'rfc' => 'TOCS510804EH4',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            122 =>
            array (
                'id' => 523,
                'numero' => 127,
                'notario' => 'GERARDO GONZÁLEZ NAVA',
                'email' => 'notariapublica127@gmail.com',
                'rfc' => 'GONG610829RD1',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            123 =>
            array (
                'id' => 524,
                'numero' => 128,
                'notario' => 'LIC. COLUMBA  ARIAS SOLIS',
                'email' => 'nota128@hotmail.com',
                'rfc' => 'AISC591011MS3',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            124 =>
            array (
                'id' => 526,
                'numero' => 130,
                'notario' => 'JAVIER MAYA MORALES',
                'email' => 'notariapublica130@hotmail.com',
                'rfc' => 'MAMJ590107R13',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            125 =>
            array (
                'id' => 527,
                'numero' => 131,
                'notario' => 'OSCAR REBOLLO LOYA',
                'email' => 'notariapublica131@gmail.com',
                'rfc' => 'RELO881025TD7',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            126 =>
            array (
                'id' => 528,
                'numero' => 132,
                'notario' => 'JORGE GUERRERO CHÁVEZ',
                'email' => 'notaria132@gmail.com',
                'rfc' => 'GUCJ611206C29',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            127 =>
            array (
                'id' => 529,
                'numero' => 133,
                'notario' => 'LIC. NELLY ESPARZA DUARTE',
                'email' => 'notaria133@hotmail.com',
                'rfc' => 'EADN770924MQ7',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            128 =>
            array (
                'id' => 530,
                'numero' => 134,
                'notario' => 'FERNANDO ORIHUELA CARMONA',
                'email' => 'orihuelacarmona134@hotmail.com',
                'rfc' => 'OICF560925DE0',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            129 =>
            array (
                'id' => 531,
                'numero' => 135,
                'notario' => 'MODESTO BARRAGÁN ROMERO',
                'email' => 'modestobarragan@prodigy.net.mx',
                'rfc' => 'BARM4201133D1',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            130 =>
            array (
                'id' => 532,
                'numero' => 136,
                'notario' => 'HORACIO ENRIQUE VILLICAÑA MORA',
                'email' => 'horaciovillicana@hotmail.com',
                'rfc' => 'VIMH800319E55',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            131 =>
            array (
                'id' => 533,
                'numero' => 137,
                'notario' => 'SALVADOR CASTILLO NÚÑEZ',
                'email' => 'notaria_137@yahoo.com.mx',
                'rfc' => 'CANS530701DW6',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            132 =>
            array (
                'id' => 534,
                'numero' => 138,
                'notario' => 'FRANCISCO JOSÉ CORONA NUÑEZ',
                'email' => 'notaria138@hotmail.com',
                'rfc' => 'CONF610409H61',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            133 =>
            array (
                'id' => 535,
                'numero' => 139,
                'notario' => 'ROGACIANO MORALES REYES',
                'email' => 'morales_notaria139@hotmail.com',
                'rfc' => 'MORR4608165H2',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            134 =>
            array (
                'id' => 536,
                'numero' => 140,
                'notario' => 'HÉCTOR SOTO SÁNCHEZ',
                'email' => 'notaria140traslados@hotmail.com',
                'rfc' => 'SOSH6802165Q3',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            135 =>
            array (
                'id' => 537,
                'numero' => 141,
                'notario' => 'ARMANDO GILBERTO MANZANO ALBA',
                'email' => 'manzanoa@armandomanzano.com',
                'rfc' => 'MAAA480204BU8',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            136 =>
            array (
                'id' => 538,
                'numero' => 142,
                'notario' => 'SABINO LÓPEZ BLANCO',
                'email' => 'notariapublica142@live.com.mx',
                'rfc' => 'LOBS650705PL5',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            137 =>
            array (
                'id' => 539,
                'numero' => 143,
                'notario' => 'JULIO ALVARO RAMÍREZ SÁNCHEZ',
                'email' => 'julionotario143@gmail.com',
                'rfc' => '',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            138 =>
            array (
                'id' => 540,
                'numero' => 144,
                'notario' => 'FRANCISCO LARA ENRIQUEZ',
                'email' => 'notaria144@hotmail.com',
                'rfc' => 'LAEF740810FR0',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            139 =>
            array (
                'id' => 541,
                'numero' => 145,
                'notario' => 'ALFONSO CARLOS VACA TAVERA',
                'email' => 'alfonsocvaca@hotmail.com',
                'rfc' => 'VATA670307HU8',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            140 =>
            array (
                'id' => 542,
                'numero' => 146,
                'notario' => 'LUZ MARÍA LAGUNAS VÁZQUEZ',
                'email' => 'luzlagunas@hotmail.com',
                'rfc' => 'LAVL650723J74',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            141 =>
            array (
                'id' => 543,
                'numero' => 147,
                'notario' => 'FABIOLA VERÓNICA SÁNCHEZ DE LA PARRA',
                'email' => 'notaria147@hotmail.com',
                'rfc' => 'SAPF700131762',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            142 =>
            array (
                'id' => 544,
                'numero' => 148,
                'notario' => 'MARIA ELENA CORNEJO CHÁVEZ',
                'email' => 'nena_notaria148@hotmail.com',
                'rfc' => 'COCE590112V40',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            143 =>
            array (
                'id' => 545,
                'numero' => 149,
                'notario' => 'GERARDO GARCÍA FERNÁNDEZ',
                'email' => 'catastro@notaria149zamora.mx',
                'rfc' => 'GAFG780429687',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            144 =>
            array (
                'id' => 546,
                'numero' => 150,
                'notario' => 'JOSÉ MIGUEL MEDINA GONZÁLEZ',
                'email' => 'notaria150@gmail.com',
                'rfc' => 'MEGM670718J55',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            145 =>
            array (
                'id' => 547,
                'numero' => 151,
                'notario' => 'JOSÉ LUIS HEREDIA SERNA',
                'email' => 'herjus03@hotmail.com',
                'rfc' => 'HESL430905HX6',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            146 =>
            array (
                'id' => 548,
                'numero' => 152,
                'notario' => 'ESTELA CARRILLO GALLEGOS',
                'email' => 'ecgn152@gmail.com',
                'rfc' => 'CAGE560626MC2',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            147 =>
            array (
                'id' => 549,
                'numero' => 153,
                'notario' => 'MARIA LUCILA ARTEAGA GARIBAY',
                'email' => 'notaria153mich@hotmail.com',
                'rfc' => 'AEGL530705UU9',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            148 =>
            array (
                'id' => 550,
                'numero' => 154,
                'notario' => 'JOSE JESUS CALDERON MORALES',
                'email' => 'notariacalderon154@hotmail.com',
                'rfc' => 'CAMJ570312R18',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            149 =>
            array (
                'id' => 551,
                'numero' => 155,
                'notario' => 'ANTONIO ALVAREZ ISAIS',
                'email' => 'notariapublica155_2@hotmail.com',
                'rfc' => 'AAIA640930T77',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            150 =>
            array (
                'id' => 552,
                'numero' => 156,
                'notario' => 'JAVIER ZUÑIGA ANDRADE',
                'email' => 'notaria.156@hotmail.com',
                'rfc' => 'ZUAJ5702046N9',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            151 =>
            array (
                'id' => 553,
                'numero' => 157,
                'notario' => 'RAÚL CRISTHIAN NAVA VALLEJO',
                'email' => 'traslados.not157@gmail.com',
                'rfc' => 'NAVR830804RC1',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            152 =>
            array (
                'id' => 554,
                'numero' => 158,
                'notario' => 'HECTOR GUSTAVO PANTOJA AYALA',
                'email' => 'tramite@notaria158.mx',
                'rfc' => 'PAAH5202036T1',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            153 =>
            array (
                'id' => 555,
                'numero' => 159,
                'notario' => 'JULIO CÉSAR CEJA ACOSTA',
                'email' => 'notario159_cjacosta@hotmail.com',
                'rfc' => 'CEAJ730105J84',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            154 =>
            array (
                'id' => 556,
                'numero' => 160,
                'notario' => 'LIC. GERARDO MUÑIZ GUIDIÑO',
                'email' => 'notaria_publica_160@hotmail.com',
                'rfc' => 'MUGG630503K38',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            155 =>
            array (
                'id' => 557,
                'numero' => 161,
                'notario' => 'LIC. SALVADOR GÁLVEZ MAGAÑA',
                'email' => 'notaria161mich@yahoo.com',
                'rfc' => 'GAMS541009Q30',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            156 =>
            array (
                'id' => 558,
                'numero' => 162,
                'notario' => 'GERARDO LUVIANO CHÁVEZ',
                'email' => 'gerardoluvianonotario162@yahoo.es',
                'rfc' => 'LUCG741129SP2',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            157 =>
            array (
                'id' => 559,
                'numero' => 163,
                'notario' => 'MARCELINO GONZÁLEZ GARCIA',
                'email' => 'notaria163traslados@gmail.com',
                'rfc' => 'GOGM680216GJ6',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            158 =>
            array (
                'id' => 560,
                'numero' => 164,
                'notario' => 'ANTONIO GUDIÑO SÁNCHEZ',
                'email' => 'np164@LIVE.COM.MX',
                'rfc' => 'GUSA681115U49',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            159 =>
            array (
                'id' => 561,
                'numero' => 165,
                'notario' => 'MIGUEL ANGEL ARELLANO PULIDO',
                'email' => 'notaria165arellano@hotmail.com',
                'rfc' => 'AEPM520511AL3',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            160 =>
            array (
                'id' => 562,
                'numero' => 166,
                'notario' => 'J. MIGUEL GARCÍA HURTADO',
                'email' => 'notariapublica166@hotmail.com',
                'rfc' => 'GAHJ541205M12',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            161 =>
            array (
                'id' => 563,
                'numero' => 167,
                'notario' => 'OMAR MARTÍNEZ LÓPEZ',
                'email' => 'notariapublica167.mich@gmail.com',
                'rfc' => 'MALO850616TP4',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            162 =>
            array (
                'id' => 564,
                'numero' => 168,
                'notario' => 'LIC. SERGIO VERGARA CRUZ',
                'email' => 'notaria_publica_168@hotmail.com',
                'rfc' => 'VECS611226TN8',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            163 =>
            array (
                'id' => 565,
                'numero' => 169,
                'notario' => 'MAURICIO MONTOYA MANZO',
                'email' => 'notariapublica169@hotmail.com',
                'rfc' => 'MOMM710913D2A',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            164 =>
            array (
                'id' => 566,
                'numero' => 170,
                'notario' => 'LIBERO MADRIGAL FLORES',
                'email' => 'rentas@notaria170.com',
                'rfc' => 'MAFL700308L78',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            165 =>
            array (
                'id' => 567,
                'numero' => 171,
            'notario' => 'DIANA LUISA TÉLLEZ BARRAGAN (ADSC.)',
                'email' => 'gestorianotaria171@outlook.com',
                'rfc' => 'TEBD710205REA',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            166 =>
            array (
                'id' => 568,
                'numero' => 172,
                'notario' => 'ROSA EUGENIA GARCÍA  VALLEJO',
                'email' => 'notariapublica_172_losreyes@hotmail.com',
                'rfc' => 'GAVR480202T74',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            167 =>
            array (
                'id' => 569,
                'numero' => 173,
                'notario' => 'LUIS FERNANDO LOYA FAMOSO',
                'email' => 'npub173traslados@gmail.com',
                'rfc' => 'LOFL8011026J3',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            168 =>
            array (
                'id' => 570,
                'numero' => 174,
                'notario' => 'MIGUEL OMAR MANZO GARCÍA',
                'email' => 'trasladosnotaria174@gmail.com',
                'rfc' => 'MAGM761129U45',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            169 =>
            array (
                'id' => 571,
                'numero' => 175,
                'notario' => 'ROSA MARIA GUTIERREZ CÁRDENAS',
                'email' => 'notaria175@hotmail.com',
                'rfc' => 'GUCR640704911',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            170 =>
            array (
                'id' => 572,
                'numero' => 176,
            'notario' => 'JAIME SANDOVAL SANCHEZ (SUST.)',
                'email' => 'notariap176@gmail.com',
                'rfc' => 'SASJ620224TD2',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            171 =>
            array (
                'id' => 573,
                'numero' => 177,
                'notario' => 'CLAUDIA ASUNCION LÓPEZ MORENO',
                'email' => 'infonota177@gmail.com',
                'rfc' => 'LOMC720131R42',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            172 =>
            array (
                'id' => 574,
                'numero' => 178,
                'notario' => 'CARINA RAMOS MENDOZA',
                'email' => 'notaria178michoacan@gmail.com',
                'rfc' => 'XAXX010101000',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            173 =>
            array (
                'id' => 575,
                'numero' => 179,
                'notario' => 'LIC. JAVIER CALDERÓN GARCÍA',
                'email' => 'notaria179michoacan@outlook.com',
                'rfc' => 'CAGJ7604138V9',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            174 =>
            array (
                'id' => 576,
                'numero' => 180,
                'notario' => 'EMILIANO MARTINEZ CORONEL',
                'email' => 'notariapublica180@gmail.com',
                'rfc' => 'MACE720917TXA',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            175 =>
            array (
                'id' => 577,
                'numero' => 181,
                'notario' => 'OMAR CÁRDENAS ORTIZ',
                'email' => 'notaria181.catastro@gmail.com',
                'rfc' => 'CAOO750531FL5',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            176 =>
            array (
                'id' => 578,
                'numero' => 182,
                'notario' => 'JAIME DARÍO OSEGUERA MÉNDEZ',
                'email' => 'notaria182tarimbaro@gmail.com',
                'rfc' => 'OEMJ711216D9A',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            177 =>
            array (
                'id' => 579,
                'numero' => 183,
                'notario' => 'LIC. ALBERTO ALEMAN LÓPEZ',
                'email' => 'notaria183aal@gmail.com',
                'rfc' => 'AELA7309303R8',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            178 =>
            array (
                'id' => 580,
                'numero' => 184,
                'notario' => 'VERONICA CALZADA MARTÍNEZ',
                'email' => 'notariavc184@hotmail.com',
                'rfc' => 'CAMV730106EQ5',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            179 =>
            array (
                'id' => 581,
                'numero' => 185,
                'notario' => 'LIC. BLAS JAIMES AVILES',
                'email' => 'notariapublica185@hotmail.com',
                'rfc' => 'JAAB8204185R7',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            180 =>
            array (
                'id' => 582,
                'numero' => 186,
                'notario' => 'LIC. LUIS SIGFRIDO GÓMEZ CAMPOS',
                'email' => 'notaria186@outlook.com',
                'rfc' => 'GOCL561019QV8',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            181 =>
            array (
                'id' => 583,
                'numero' => 187,
                'notario' => 'LIC. MARTHA ISELA SÁNCHEZ CORIA',
                'email' => 'notaria187uruapan@gmail.com',
                'rfc' => 'SACM700608417',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            182 =>
            array (
                'id' => 584,
                'numero' => 188,
                'notario' => 'FRANCISCO JOSÉ CORONA TORRES',
                'email' => 'notario188@hotmail.com',
                'rfc' => 'COTF8103062C1',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            183 =>
            array (
                'id' => 585,
                'numero' => 189,
                'notario' => 'JOSE CORTES VALDESPINO',
                'email' => 'notaria189mich@gmail.com',
                'rfc' => 'COVJ730618M24',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            184 =>
            array (
                'id' => 586,
                'numero' => 190,
                'notario' => 'EMILIANO PEDRAZA HINOJOSA',
                'email' => 'contabilidad.notaria190@gmail.com',
                'rfc' => 'PEHE720304D80',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            185 =>
            array (
                'id' => 587,
                'numero' => 191,
                'notario' => 'MARÍA DE JESÚS OLIVEROS VALDOVINOS',
                'email' => 'notariamich191@hotmail.com',
                'rfc' => 'OIVJ721224RPA',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            186 =>
            array (
                'id' => 588,
                'numero' => 192,
                'notario' => 'LIC. CLAUDIA OROPEZA MIRANDA',
                'email' => 'notaria192morelia@gmail.com',
                'rfc' => 'OOMC731113T72',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            187 =>
            array (
                'id' => 589,
                'numero' => 193,
                'notario' => 'ROSALBA ELVIRA RIOS',
                'email' => 'notaria193michoacan@gmail.com',
                'rfc' => 'EIRR730116F7A',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            188 =>
            array (
                'id' => 590,
                'numero' => 195,
                'notario' => 'LUIS ALBERTO MONTAÑO GARCÍA',
                'email' => 'notaria195mich@hotmail.com',
                'rfc' => 'MOGL701026479',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            189 =>
            array (
                'id' => 591,
                'numero' => 196,
            'notario' => 'HAYDE CORONA VEGA (ADS.)',
                'email' => 'notariapublica196@outlook.com',
                'rfc' => 'COVH770809LC8',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            190 =>
            array (
                'id' => 592,
                'numero' => 199,
                'notario' => 'DIEGO ANITA GUTÍERREZ',
                'email' => 'diegoanitagutierrez@gmail.com',
                'rfc' => 'AIGD8403138T5',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            191 =>
            array (
                'id' => 593,
                'numero' => 200,
                'notario' => 'ADRIÁN MAGAÑA MENDOZA',
                'email' => 'notario200mich@gmail.com',
                'rfc' => 'MAMA771209PM1',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
            192 =>
            array (
                'id' => 594,
                'numero' => 203,
                'notario' => 'CINTHYA CRISTINA ORTIZ CORONA',
                'email' => 'notariapublicamich203@gmail.com',
                'rfc' => 'OICC910101CI4',
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-06-08 14:38:46',
                'updated_at' => '2023-06-08 14:38:34',
            ),
        ));
    }
}
