<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ServiciosTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('servicios')->delete();

        \DB::table('servicios')->insert(array (
            0 =>
            array (
                'id' => 1,
                'nombre' => 'Cuando se trate de uno o hasta cinco tomos o libros índice',
                'tipo' => 'uma',
                'estado' => 'activo',
                'umas' => '1.00',
                'ordinario' => '104.00',
                'urgente' => '0.00',
                'extra_urgente' => '0.00',
                'material' => '2403502413',
                'clave_ingreso' => 'DC93',
                'operacion_principal' => '2403',
                'operacion_parcial' => '5024',
                'categoria_servicio_id' => 1,
                'creado_por' => 1,
                'actualizado_por' => 1,
                'created_at' => '2023-05-09 17:36:09',
                'updated_at' => '2023-05-11 13:00:12',
            ),
            1 =>
            array (
                'id' => 2,
            'nombre' => 'Copias certificadas (por página)',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '45.00',
                'urgente' => '90.00',
                'extra_urgente' => '135.00',
                'material' => '2403064513',
                'clave_ingreso' => 'DL13',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0645',
                'categoria_servicio_id' => 1,
                'creado_por' => 1,
                'actualizado_por' => 1,
                'created_at' => '2023-05-09 17:38:33',
                'updated_at' => '2023-06-07 13:52:56',
            ),
            2 =>
            array (
                'id' => 3,
                'nombre' => 'Búsqueda de antecedente de 1 a 10',
                'tipo' => 'uma',
                'estado' => 'activo',
                'umas' => '1.00',
                'ordinario' => '104.00',
                'urgente' => '0.00',
                'extra_urgente' => '0.00',
                'material' => '2403502113',
                'clave_ingreso' => 'DC90',
                'operacion_principal' => '2403',
                'operacion_parcial' => '5021',
                'categoria_servicio_id' => 1,
                'creado_por' => 1,
                'actualizado_por' => 1,
                'created_at' => '2023-05-11 12:42:06',
                'updated_at' => '2023-06-08 11:32:30',
            ),
            3 =>
            array (
                'id' => 4,
                'nombre' => 'Búsqueda de bienes por índices de 11 a 20.',
                'tipo' => 'uma',
                'estado' => 'activo',
                'umas' => '2.00',
                'ordinario' => '208.00',
                'urgente' => '0.00',
                'extra_urgente' => '0.00',
                'material' => '2403502213',
                'clave_ingreso' => 'DC91',
                'operacion_principal' => '2403',
                'operacion_parcial' => '5022',
                'categoria_servicio_id' => 1,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2023-05-11 12:42:31',
                'updated_at' => '2023-05-11 12:42:31',
            ),
            4 =>
            array (
                'id' => 5,
                'nombre' => 'Búsqueda de bienes por índices de 21 o más.',
                'tipo' => 'uma',
                'estado' => 'activo',
                'umas' => '3.00',
                'ordinario' => '312.00',
                'urgente' => '0.00',
                'extra_urgente' => '0.00',
                'material' => '2403502313',
                'clave_ingreso' => 'DC92',
                'operacion_principal' => '2403',
                'operacion_parcial' => '5023',
                'categoria_servicio_id' => 1,
                'creado_por' => 1,
                'actualizado_por' => 1,
                'created_at' => '2023-05-11 12:42:54',
                'updated_at' => '2023-06-07 13:52:02',
            ),
            5 =>
            array (
                'id' => 6,
            'nombre' => 'Copias simples (por página)',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '27.00',
                'urgente' => '54.00',
                'extra_urgente' => '81.00',
                'material' => '2403065013',
                'clave_ingreso' => 'DL14',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0650',
                'categoria_servicio_id' => 1,
                'creado_por' => 1,
                'actualizado_por' => 1,
                'created_at' => '2023-05-11 13:02:12',
                'updated_at' => '2023-06-07 13:50:40',
            ),
            6 =>
            array (
                'id' => 7,
                'nombre' => 'No habitacional rustico',
                'tipo' => 'uma',
                'estado' => 'activo',
                'umas' => '6.00',
                'ordinario' => '622.00',
                'urgente' => '1244.00',
                'extra_urgente' => '1866.00',
                'material' => '2403067513',
                'clave_ingreso' => 'D114',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0675',
                'categoria_servicio_id' => 5,
                'creado_por' => 1,
                'actualizado_por' => 1,
                'created_at' => '2023-10-11 13:31:09',
                'updated_at' => '2023-10-11 13:32:22',
            ),
            7 =>
            array (
                'id' => 8,
                'nombre' => 'No habitacional urbano',
                'tipo' => 'uma',
                'estado' => 'activo',
                'umas' => '16.00',
                'ordinario' => '1660.00',
                'urgente' => '3320.00',
                'extra_urgente' => '4980.00',
                'material' => '2403067013',
                'clave_ingreso' => 'D113',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0670',
                'categoria_servicio_id' => 4,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2023-10-11 15:23:00',
                'updated_at' => '2023-10-11 15:23:00',
            ),
            8 =>
            array (
                'id' => 9,
                'nombre' => 'Habitacional cuyo valor no exceda $946,110.00',
                'tipo' => 'uma',
                'estado' => 'activo',
                'umas' => '8.50',
                'ordinario' => '882.00',
                'urgente' => '1764.00',
                'extra_urgente' => '2646.00',
                'material' => '2403068013',
                'clave_ingreso' => 'D115',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0680',
                'categoria_servicio_id' => 4,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2023-10-11 15:26:24',
                'updated_at' => '2023-10-11 15:26:24',
            ),
            9 =>
            array (
                'id' => 10,
                'nombre' => 'Habitacional cuyo valor exceda $946,110.00',
                'tipo' => 'uma',
                'estado' => 'activo',
                'umas' => '11.50',
                'ordinario' => '1193.00',
                'urgente' => '2386.00',
                'extra_urgente' => '3579.00',
                'material' => '2403068513',
                'clave_ingreso' => 'D116',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0685',
                'categoria_servicio_id' => 4,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2023-10-11 15:27:45',
                'updated_at' => '2023-10-11 15:27:45',
            ),
            10 =>
            array (
                'id' => 11,
                'nombre' => 'Servidumbre de paso por cada inmueble',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '429.00',
                'urgente' => '858.00',
                'extra_urgente' => '1287.00',
                'material' => '2403069513',
                'clave_ingreso' => 'D118',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0695',
                'categoria_servicio_id' => 4,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2023-10-11 15:28:32',
                'updated_at' => '2023-10-11 15:28:32',
            ),
            11 =>
            array (
                'id' => 12,
                'nombre' => 'Fraccionamientos, lotificaciones, habitacionales recidencial',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '81.00',
                'urgente' => '0.00',
                'extra_urgente' => '0.00',
                'material' => '2403072013',
                'clave_ingreso' => 'D123',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0720',
                'categoria_servicio_id' => 4,
                'creado_por' => 1,
                'actualizado_por' => 1,
                'created_at' => '2023-10-11 15:29:49',
                'updated_at' => '2023-10-12 12:09:58',
            ),
            12 =>
            array (
                'id' => 13,
                'nombre' => 'Fraccionamientos, lotificaciones, habitacionales tipo medio',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '32.00',
                'urgente' => '0.00',
                'extra_urgente' => '0.00',
                'material' => '2403070013',
                'clave_ingreso' => 'D119',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0700',
                'categoria_servicio_id' => 4,
                'creado_por' => 1,
                'actualizado_por' => 1,
                'created_at' => '2023-10-11 15:30:30',
                'updated_at' => '2023-10-12 12:09:53',
            ),
            13 =>
            array (
                'id' => 14,
                'nombre' => 'Fraccionamientos, lotificaciones, habitacionales popular',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '32.00',
                'urgente' => '0.00',
                'extra_urgente' => '0.00',
                'material' => '2403070513',
                'clave_ingreso' => 'D120',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0705',
                'categoria_servicio_id' => 4,
                'creado_por' => 1,
                'actualizado_por' => 1,
                'created_at' => '2023-10-11 15:31:05',
                'updated_at' => '2023-10-12 12:09:48',
            ),
            14 =>
            array (
                'id' => 15,
                'nombre' => 'Fraccionamientos, lotificaciones, habitacionales campestre',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '117.00',
                'urgente' => '0.00',
                'extra_urgente' => '0.00',
                'material' => '2403071013',
                'clave_ingreso' => 'D121',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0710',
                'categoria_servicio_id' => 4,
                'creado_por' => 1,
                'actualizado_por' => 1,
                'created_at' => '2023-10-11 15:32:28',
                'updated_at' => '2023-10-12 12:09:35',
            ),
            15 =>
            array (
                'id' => 16,
                'nombre' => 'Lotificación industrial y comercial',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '228.00',
                'urgente' => '456.00',
                'extra_urgente' => '684.00',
                'material' => '2403072513',
                'clave_ingreso' => 'D124',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0725',
                'categoria_servicio_id' => 4,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2023-10-11 15:33:22',
                'updated_at' => '2023-10-11 15:33:22',
            ),
            16 =>
            array (
                'id' => 17,
                'nombre' => 'Régimen de propiedad en condominio habitacional por cada vivienda',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '81.00',
                'urgente' => '162.00',
                'extra_urgente' => '243.00',
                'material' => '2403073513',
                'clave_ingreso' => 'D126',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0735',
                'categoria_servicio_id' => 4,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2023-10-11 15:34:39',
                'updated_at' => '2023-10-11 15:34:39',
            ),
            17 =>
            array (
                'id' => 18,
                'nombre' => 'Régimen de propiedad en condominio por local comercial',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '132.00',
                'urgente' => '264.00',
                'extra_urgente' => '396.00',
                'material' => '2403073013',
                'clave_ingreso' => 'D125',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0730',
                'categoria_servicio_id' => 4,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2023-10-11 15:35:24',
                'updated_at' => '2023-10-11 15:35:24',
            ),
            18 =>
            array (
                'id' => 19,
                'nombre' => 'No habitacional rustico',
                'tipo' => 'uma',
                'estado' => 'activo',
                'umas' => '6.00',
                'ordinario' => '622.00',
                'urgente' => '1244.00',
                'extra_urgente' => '1866.00',
                'material' => '2403067013',
                'clave_ingreso' => 'D114',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0670',
                'categoria_servicio_id' => 4,
                'creado_por' => 1,
                'actualizado_por' => 1,
                'created_at' => '2023-10-11 15:37:59',
                'updated_at' => '2023-10-11 17:05:23',
            ),
            19 =>
            array (
                'id' => 20,
                'nombre' => 'Fraccionamientos, lotificaciones, habitacionales rustico',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '81.00',
                'urgente' => '0.00',
                'extra_urgente' => '0.00',
                'material' => '2403071513',
                'clave_ingreso' => 'D122',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0715',
                'categoria_servicio_id' => 4,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2023-10-12 12:11:45',
                'updated_at' => '2023-10-12 12:11:45',
            ),
            20 =>
            array (
                'id' => 21,
                'nombre' => 'Tratándose de testimonios notariales que provengan de otras entidades federativas',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '1986.00',
                'urgente' => '3972.00',
                'extra_urgente' => '5958.00',
                'material' => '2403177013',
                'clave_ingreso' => 'D158',
                'operacion_principal' => '2403',
                'operacion_parcial' => '2403',
                'categoria_servicio_id' => 4,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2023-12-20 13:48:14',
                'updated_at' => '2023-12-20 13:48:14',
            ),
        ));


    }
}
